/*
  ====================================================
  商品資料檔（可隨時編輯替換）
  ====================================================
  只要修改這個檔案，網頁內容就會自動更新，不需要動 index.html。

  每一筆商品欄位說明：
    category    分類，必須跟下面 CATEGORIES 清單裡的 id 對應
    brand       品牌名稱
    name        商品名稱
    spec        規格／容量
    price       售價（數字，不用打 NT$）
    originalPrice  原價（選填。若有填，會顯示劃線原價 + 折扣標籤；不需要就整行刪掉或設 null）
    note        備註（選填，例如「新品」「熱銷」「限量」）
    image       圖片檔名，圖片放在 images 資料夾裡
    desc        產品簡介（點擊圖片時彈出的介紹文字，可自行改寫）

  ※ 目前售價為「示意範例」，請自行改成實際售價。
  ※ desc 產品簡介為初稿文字，建議依實際商品資訊確認後再對外使用。
  ====================================================
*/

const CATEGORIES = [
  { id: "shampoo",    name: "洗髮 Shampoo" },
  { id: "conditioner",name: "潤髮 Conditioner" },
  { id: "treatment",  name: "護髮膜 Treatment" },
  { id: "leave-in",   name: "免沖洗 / 精華油 Leave-in & Oil" },
  { id: "styling",    name: "造型 Styling" },
  { id: "scalp",      name: "頭皮養護 Scalp Care" },
  { id: "color",      name: "矯色洗 Color Shampoo" },
  { id: "promotion",  name: "限量活動 Promotion" },
];

const PRODUCTS = [
  // ---------- 洗髮 Shampoo ----------


{
    category: "shampoo",
    brand: "EDNA",
    name: "賦檸洗髮露 500ML",
    spec: "500ml",
    price: 980,
    originalPrice: null,
    note: "",
    image: "S2.webp",
    desc: "專為敏感頭皮設計，採用專利發酵萃取，溫和淨化頭皮、減少皮脂累積，並搭配辛醯基甘氨酸平衡頭皮微生態。燕麥生物鹼，有效舒緩不適，維持頭皮健康穩定。",
  },
  {
    category: "shampoo",
    brand: "EDNA",
    name: "蘊活化洗髮露",
    spec: "500ml",
    price: 980,
    originalPrice: null,
    note: "",
    image: "S4.webp",
    desc: "Procapil專利活性成份，強健髮根活絡毛髮，防止毛髮斷裂；九合一植萃強化頭皮屏障，抵禦污染；咖啡因滋養活力，全面活化頭皮和髮絲健康。",
  },
  {
    category: "shampoo",
    brand: "EDNA",
    name: "恬栗洗髮露",
    spec: "500ml",
    price: 850,
    originalPrice: null,
    note: "",
    image: "S1.webp",
    desc: "秘魯龍血萃取修復屏障，改善乾燥；天然認證鼠尾草籽萃取，預防化學損傷破壞頭髮的蛋白鏈結，合成仿生角質層有助為維持髮質；有機蠟菊萃取液深層滋養秀髮，恢復毛囊活力。使髮絲水潤強韌不易斷裂。",
  },
  {
    category: "shampoo",
    brand: "óben",
    name: "巴黎高牆保濕洗髮露500ML",
    spec: "500ml",
    price: 1500,
    originalPrice: null,
    note: "",
    image: "S9.jpg",
    desc: "主打保濕抗氧化與蓬鬆空氣感。核心成分包含水解小麥蛋白、醣基海藻糖、蠟菊萃取液及維他命B5，能深度滋潤並增加髮絲強韌度。",
  },
  {
    category: "shampoo",
    brand: "TOKIO INKARAMI",
    name: "NEW 喚羽淨露",
    spec: "400ml",
    price: 2200,
    originalPrice: null,
    note: "",
    image: "S17.jpg",
    desc: "輕度受損髮專用，使用牛磺酸的低刺激胺基酸類髮浴，打造柔順、有光澤的輕盈髮質。",
  },
  {
    category: "shampoo",
    brand: "TOKIO INKARAMI",
    name: "NEW 金·喚羽淨露",
    spec: "400ml",
    price: 2700,
    originalPrice: null,
    note: "",
    image: "S16.jpg",
    desc: "高度受損髮專用，使用絲蛋白與膠原蛋白清潔成分的胺基酸型髮浴，重建髮絲的強韌質感。",
  },
  {
    category: "shampoo",
    brand: "óben",
    name: "塞納河畔控油洗髮露500ML",
    spec: "500ml",
    price: 1500,
    originalPrice: null,
    note: "",
    image: "S10.jpg",
    desc: "針對油性、容易扁塌的頭皮與髮絲設計，強調深度清潔毛孔並有效收斂多餘油脂。",
  },
  {
    category: "shampoo",
    brand: "OOLABOO",
    name: "歐拉布-綠竹重建洗髮精1000ML",
    spec: "1000ml",
    price: 3360,
    originalPrice: null,
    note: "",
    image: "S21.jpg",
    desc: "具有高效保濕因子、抗氧化、抑菌，針對脆弱、化學傷害的受損髮提供重新強化結構的修護程序，提升髮質強韌度，使頭髮呈現線條感。",
  },
  {
    category: "shampoo",
    brand: "óben",
    name: "盧森堡公園舒敏洗髮露500ML",
    spec: "500ml",
    price: 1500,
    originalPrice: null,
    note: "",
    image: "S11.jpg",
    desc: "添加大西洋雪松精油、葡糖酸鋅、甘草酸胺與咖啡因，專為舒緩頭皮不適與日常潔淨設計。",
  },
  {
    category: "shampoo",
    brand: "óben",
    name: "巴黎高牆保濕洗髮露800ML",
    spec: "800ml",
    price: 2200,
    originalPrice: null,
    note: "",
    image: "S12.jpg",
    desc: "主打保濕抗氧化與蓬鬆空氣感。核心成分包含水解小麥蛋白、醣基海藻糖、蠟菊萃取液及維他命B5，能深度滋潤並增加髮絲強韌度。",
  },
  {
    category: "shampoo",
    brand: "óben",
    name: "塞納河畔控油洗髮露800ML",
    spec: "800ml",
    price: 2200,
    originalPrice: null,
    note: "",
    image: "S13.jpg",
    desc: "針對油性、容易扁塌的頭皮與髮絲設計，強調深度清潔毛孔並有效收斂多餘油脂。",
  },
  {
    category: "shampoo",
    brand: "óben",
    name: "盧森堡公園舒敏洗髮露800ML",
    spec: "800ml",
    price: 2200,
    originalPrice: null,
    note: "",
    image: "S14.jpg",
    desc: "添加大西洋雪松精油、葡糖酸鋅、甘草酸胺與咖啡因，專為舒緩頭皮不適與日常潔淨設計。",
  },


  // ---------- 潤髮 Conditioner ----------


  {
    category: "conditioner",
    brand: "óben",
    name: "杜勒麗花園護色潤髮素500ml",
    spec: "500ml",
    price: 1500,
    originalPrice: null,
    note: "",
    image: "C5.jpg",
    desc: "主打鎖色、保濕與修護，能有效維持染後髮絲的光澤與柔順。",
  },
  {
    category: "conditioner",
    brand: "óben",
    name: "杜勒麗花園護色潤髮素800ml",
    spec: "800ml",
    price: 2200,
    originalPrice: null,
    note: "",
    image: "C6.jpg",
    desc: "主打鎖色、保濕與修護，能有效維持染後髮絲的光澤與柔順。",
  },


  // ---------- 護髮膜 Treatment ----------


  {
    category: "treatment",
    brand: "TOKIO INKARAMI",
    name: "NEW 金·喚羽凝脂",
    spec: "400ml",
    price: 2700,
    originalPrice: null,
    note: "",
    image: "C9.jpg",
    desc: "具優秀護髮效果的配方成份，搭配獨家配方「外部凝聚結合成分」，可以有效將角蛋白滲透進毛髮內部結合，打造出極致修護能力的洗髮精與護髮產品。",
  },
  {
    category: "treatment",
    brand: "SUITE",
    name: "滋養髮膜1000ml",
    spec: "1000ml",
    price: 2700,
    originalPrice: null,
    note: "",
    image: "C3.jpg",
    desc: "含摩洛哥堅果油、棕梠油等萃取成分，強效滋養保濕，增加秀髮光澤感。",
  },
  {
    category: "treatment",
    brand: "TOKIO INKARAMI",
    name: "NEW 喚羽凝脂",
    spec: "400ml",
    price: 2200,
    originalPrice: null,
    note: "",
    image: "C11.jpg",
    desc: "由多種角蛋白(修護劑)賦予頭髮韌性並帶來修護效果，利用健康頭髮擁有的脂質成分進行保濕。",
  },
  {
    category: "treatment",
    brand: "SUITE",
    name: "滋養髮膜500ml",
    spec: "500ml",
    price: 1700,
    originalPrice: null,
    note: "",
    image: "C4.jpg",
    desc: "含摩洛哥堅果油、棕梠油等萃取成分，強效滋養保濕，增加秀髮光澤感。",
  },

  // ---------- 免沖洗 / 精華油 Leave-in & Oil ----------


  {
    category: "leave-in",
    brand: "MILK_SHAKE",
    name: "醇香果油50ML",
    spec: "50ml",
    price: 980,
    originalPrice: null,
    note: "",
    image: "O2.jpg",
    desc: "有機堅果含有高單位的脂肪酸，具有對肌膚與頭髮滋潤修復的特性，能保護頭髮免於環境因子的傷害。",
  },
  {
    category: "leave-in",
    brand: "TOKIO INKARAMI",
    name: "NEW 喚羽恆潤",
    spec: "50g",
    price: 880,
    originalPrice: null,
    note: "",
    image: "C10.jpg",
    desc: "各種髮質適用，可收斂無法緊閉的髮絲，同時補充大量質感成分，可調節水分、油份平衡。",
  },
  {
    category: "leave-in",
    brand: "OOLABOO",
    name: "歐拉布-松露凝光露50ML",
    spec: "50ml",
    price: 1760,
    originalPrice: null,
    note: "",
    image: "O8.webp",
    desc: "高度光澤滋養油，含有松露油、澳洲胡桃果油、摩洛哥堅果油、絲蛋白與天然防曬成分，其中護色因子能抵禦外在環境因素，適用於所有髮質。",
  },
  {
    category: "leave-in",
    brand: "TOKIO INKARAMI",
    name: "NEW 金·喚羽京澤",
    spec: "100ml",
    price: 1900,
    originalPrice: null,
    note: "",
    image: "C8.jpg",
    desc: "噴霧型的免沖洗護髮產品。立即補充修護頭髮角蛋白、油份、水份，賦予頭髮保濕、柔順、光澤與彈性的最佳狀態。",
  },
  {
    category: "leave-in",
    brand: "Purifica MiL",
    name: "雪透光賦活乳",
    spec: "150ml",
    price: 1100,
    originalPrice: null,
    note: "",
    image: "C14.jpg",
    desc: "抑制毛燥、維持長效水潤感，將水分緊緊鎖在秀髮裡長效水潤保護秀髮不再乾燥。",
  },
  {
    category: "leave-in",
    brand: "TOKIO INKARAMI",
    name: "NEW 喚羽精華",
    spec: "100ml",
    price: 1700,
    originalPrice: null,
    note: "",
    image: "C12.jpg",
    desc: "絲蛋白（保濕劑）與角鯊烷（保濕劑）賦予毛鱗片滋潤，打造手指滑過時的輕盈質感。富勒烯與頭髮保護成分防止紫外線造成的傷害。",
  },
  {
    category: "leave-in",
    brand: "napla N.",
    name: "N多重修護滋養油 150ML",
    spec: "150ml",
    price: 1050,
    originalPrice: null,
    note: "",
    image: "O5.jpg",
    desc: "結合3大高效護髮功效—熱反應修護・鎖色護色・水潤屏障，能針對多重髮質損傷進行全方位的修護保養。",
  },

  // ---------- 造型 Styling ----------


  {
    category: "styling",
    brand: "FIOLE",
    name: "幾何圖騰 空氣感造型髮蠟",
    spec: "80g",
    price: 950,
    originalPrice: null,
    note: "",
    image: "Z13.jpg",
    desc: "能控制髮量豐厚及輕薄，打造柔和空氣感的輕爽型髮蠟。",
  },
  {
    category: "styling",
    brand: "LABEL.M",
    name: "塑捲活力乳150ML",
    spec: "150ml",
    price: 1100,
    originalPrice: null,
    note: "",
    image: "Z2.jpg",
    desc: "專為捲髮打造的造型品，鎖住頭髮水份且抗毛燥，提供捲髮柔順修護效果。",
  },
  {
    category: "styling",
    brand: "DEPOT",
    name: "302 凝土髮霜 75ML",
    spec: "75ml",
    price: 1080,
    originalPrice: null,
    note: "",
    image: "Z3.webp",
    desc: "專為細軟髮設計的霧面塑型造型品， 好清洗、好塑型、不黏膩，適合自然蓬鬆感的造型。",
  },
  {
    category: "styling",
    brand: "DEPOT",
    name: "306 強力噴霧(量感強力定型) 400ML",
    spec: "400ml",
    price: 1080,
    originalPrice: null,
    note: "",
    image: "Z4.jpg",
    desc: "強力量感定型噴霧，定型力佳，可讓髮型長效維持，定型後仍保有柔軟的髮質觸感，適合做為強效定型的最後一道步驟。",
  },
  {
    category: "styling",
    brand: "napla N.",
    name: "N定妝造型霧 5  180G",
    spec: "180g",
    price: 780,
    originalPrice: null,
    note: "",
    image: "Z5.jpg",
    desc: "能立即瞬效定型的造型噴霧。幾乎不含水分的質地可避免影響髮型濕度與重量，維持造型。",
  },
  {
    category: "styling",
    brand: "LABEL.M",
    name: "捲捲活力凝露250ML",
    spec: "250ml",
    price: 1200,
    originalPrice: null,
    note: "",
    image: "Z1.jpg",
    desc: "提供頭髮整天所需滋潤，含有豐富的維他命以及胺基酸可達到修護滋養功效。可鎖住頭髮水份，完美快速讓捲髮重新塑型，不需要沖水的造型修護素。",
  },
  {
    category: "styling",
    brand: "MILBON",
    name: "雪球藍",
    spec: "200g",
    price: 900,
    originalPrice: null,
    note: "",
    image: "M7.jpg",
    desc: "",
  },
  {
    category: "styling",
    brand: "OOLABOO",
    name: "歐拉布-絕代風華4D泡泡",
    spec: "250g",
    price: 1320,
    originalPrice: null,
    note: "",
    image: "M8.jpg",
    desc: "質地輕盈的慕絲狀造型品，主打不黏膩、具備獨家記形科技，能長時間維持秀髮的豐盈、支撐感與捲度。",
  },
  {
    category: "styling",
    brand: "napla N.",
    name: "N乳油木輕質油 150ML",
    spec: "150ml",
    price: 1050,
    originalPrice: null,
    note: "",
    image: "O4.jpg",
    desc: "超高壓處理的三種植物精油，輕盈不黏膩，瞬時滋潤髮絲，打造健康彈潤秀髮。",
  },
  {
    category: "styling",
    brand: "MILK_SHAKE",
    name: "超保濕護髮泡沫",
    spec: "200ml",
    price: 880,
    originalPrice: null,
    note: "",
    image: "M1.webp",
    desc: "乾性髮質適用，維持髮絲保濕平衡，呈現柔軟光澤好梳理。",
  },
  {
    category: "styling",
    brand: "MILK_SHAKE",
    name: "醇香護髮泡沫(花香版)",
    spec: "200ml",
    price: 880,
    originalPrice: null,
    note: "",
    image: "M3.jpg",
    desc: "乾性髮質適用，維持髮絲保濕平衡，呈現柔軟光澤好梳理。",
  },
  {
    category: "styling",
    brand: "FIOLE",
    name: "幾何圖騰 輕柔造型髮蠟",
    spec: "80g",
    price: 950,
    originalPrice: null,
    note: "",
    image: "Z8.jpg",
    desc: "以吹風機吹整出輕盈造型的軟式髮蠟，呈現自然動感線條。",
  },
  {
    category: "styling",
    brand: "napla N.",
    name: "N彈力泡沫慕斯",
    spec: "200g",
    price: 680,
    originalPrice: null,
    note: "",
    image: "M5.jpg",
    desc: "極致光澤，閃亮Q彈。緊密貼合每一根髮絲，賦予恰到好處的定型力，同時帶來絲質滑順與波峰感。",
  },
  {
    category: "styling",
    brand: "napla N.",
    name: "N水潤泡沫慕斯",
    spec: "200g",
    price: 680,
    originalPrice: null,
    note: "",
    image: "M6.jpg",
    desc: "自然垂落的垂墜感，搖曳感。在抑制毛躁不僵硬，展現出光澤與水潤的捲髮造型。",
  },
  {
    category: "styling",
    brand: "FIOLE",
    name: "幾何圖騰 超強力造型髮蠟",
    spec: "80g",
    price: 950,
    originalPrice: null,
    note: "",
    image: "Z7.jpg",
    desc: "讓髮根持久站立，長時間維持的超強力硬式髮蠟，速乾、具乾爽感。",
  },
  {
    category: "styling",
    brand: "DEPOT",
    name: "317曲線強化慕斯",
    spec: "200ml",
    price: 1180,
    originalPrice: null,
    note: "",
    image: "M4.webp",
    desc: "有效撫平毛躁，打造蓬鬆捲度，提升髮絲彈性與輪廓感，中度定型力。",
  },

  // ---------- 矯色洗髮露 Color Shampoo ----------


  {
    category: "color",
    brand: "FIOLE",
    name: "露西亞增色髮露-奶霜棕250ML/1000ML",
    spec: "250ml/1000ml",
    price: 800/1050,
    originalPrice: null,
    note: "",
    image: "L9.jpg",
    desc: "延續灰色特有的髮色質感，採用胺基酸系清潔配方，溫柔修護重複染髮造成的頭髮及頭皮傷害。",
  },
  {
    category: "color",
    brand: "FIOLE",
    name: "露西亞增色髮露-清水灰1000ML",
    spec: "1000ml",
    price: 1050,
    originalPrice: null,
    note: "",
    image: "L8.jpg",
    desc: "延續灰色特有的髮色質感，採用胺基酸系清潔配方，溫柔修護重複染髮造成的頭髮及頭皮傷害。",
  },
  {
    category: "color",
    brand: "FIOLE",
    name: "露西亞增色髮露-極光紫250ML",
    spec: "250ml",
    price: 800,
    originalPrice: null,
    note: "",
    image: "L6.jpg",
    desc: "抵銷高明度髮色中的橘、黃色素，矯色避免枯黃跑色，採用胺基酸系清潔配方，溫柔修護重複染髮造成的頭髮及頭皮傷害。",
  },
  {
    category: "color",
    brand: "FIOLE",
    name: "露西亞增色髮露-琥珀橘250ML",
    spec: "250ml",
    price: 800,
    originalPrice: null,
    note: "",
    image: "L5.jpg",
    desc: "延續有華麗感的橘色髮色，採用胺基酸系清潔配方，溫柔修護重複染髮造成的頭髮及頭皮傷害。",
  },
  {
    category: "color",
    brand: "FIOLE",
    name: "露西亞增色髮露-仙氣粉250ML",
    spec: "250ml",
    price: 800,
    originalPrice: null,
    note: "",
    image: "L4.jpg",
    desc: "增強粉色調，延長髮色的持久性，採用胺基酸系清潔配方，溫柔修護重複染髮造成的頭髮及頭皮傷害。",
  },
  {
    category: "color",
    brand: "FIOLE",
    name: "露西亞增色髮露-極光紫1000ML",
    spec: "1000ml",
    price: 1050,
    originalPrice: null,
    note: "",
    image: "L3.jpg",
    desc: "抵銷高明度髮色中的橘、黃色素，矯色避免枯黃跑色，採用胺基酸系清潔配方，溫柔修護重複染髮造成的頭髮及頭皮傷害。",
  },
  {
    category: "color",
    brand: "FIOLE",
    name: "露西亞增色髮露-琥珀橘1000ML",
    spec: "1000ml",
    price: 1050,
    originalPrice: null,
    note: "",
    image: "L2.jpg",
    desc: "延續有華麗感的橘色髮色，採用胺基酸系清潔配方，溫柔修護重複染髮造成的頭髮及頭皮傷害。",
  },
  {
    category: "color",
    brand: "FIOLE",
    name: "露西亞增色髮露-布朗棕250ML",
    spec: "250ml",
    price: 800,
    originalPrice: null,
    note: "",
    image: "L10.jpg",
    desc: "咖啡色系髮色專用，打造清透棕色效果、延續咖啡色的質感，採用胺基酸系清潔配方，溫柔修護重複染髮造成的頭髮及頭皮傷害。",
  },
  {
    category: "color",
    brand: "FIOLE",
    name: "露西亞增色髮露-仙氣粉1000ML",
    spec: "1000ml",
    price: 1050,
    originalPrice: null,
    note: "",
    image: "L1.jpg",
    desc: "增強粉色調，延長髮色的持久性，採用胺基酸系清潔配方，溫柔修護重複染髮造成的頭髮及頭皮傷害。",
  },
  {
    category: "color",
    brand: "FIOLE",
    name: "露西亞增色髮露-清水灰250ML",
    spec: "250ml",
    price: 800,
    originalPrice: null,
    note: "",
    image: "L7.jpg",
    desc: "增強粉色調，延長髮色的持久性，採用胺基酸系清潔配方，溫柔修護重複染髮造成的頭髮及頭皮傷害。",
  },

  // ---------- 頭皮養護 Scalp Care ----------

  {
    category: "scalp",
    brand: "VIRTUE",
    name: "髮肌密集呵護活泉",
    spec: "120ml",
    price: 1780,
    originalPrice: null,
    note: "限量",
    image: "C1.jpg",
    desc: "為疲勞的毛囊補充能量，滋養脆弱及新生髮，使髮絲增厚並茁壯生長。",
  },




];
